authProviders:
  - name: tokenx
    discoveryUrl: http://localhost:8081/default/.well-known/openid-configuration
    tokenEndpointUrl: http://localhost:8081/default/token
    clientId: paw-arbeidssoekerregisteret-api-oppslag
    claims:
      map:
        - acr=Level4
        - acr=idporten-loa-high
      combineWithOr: true
  - name: azure
    discoveryUrl: http://localhost:8081/default/.well-known/openid-configuration
    tokenEndpointUrl: http://localhost:8081/default/token
    clientId: paw-arbeidssoekerregisteret-api-oppslag
    claims:
      map:
        - NAVident
      combineWithOr: false
poaoClientConfig:
  url: http://localhost:8090/poao-tilgang/
  scope: api://test.test.poao-tilgang/.default
database:
  host: localhost
  port: 5432
  username: admin
  password: admin
  name: arbeidssoekerregisteretapioppslag
kafka:
  gruppeId: paw.arbeidsseokerregisteret-api-oppslag-v1
  periodeTopic: paw.arbeidssokerperioder-v1
  opplysningerOmArbeidssoekerTopic: paw.opplysninger-om-arbeidssoeker-v1
  profileringTopic: paw.arbeidssoker-profilering-v1
  serverConfig:
    autentisering: PLAIN
    kafkaBrokers: localhost:9092
  schemaRegistryConfig:
    url: http://localhost:8082

