apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: paw-arbeidssoekerregisteret-api-oppslag
  namespace: paw
  labels:
    team: paw
spec:
  image: {{ image }}
  ingresses:
    - https://oppslag-arbeidssoekerregisteret.intern.nav.no
  port: 8080
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - NAVident
  tokenx:
    enabled: true
  kafka:
    pool: nav-prod
  envFrom:
    - secret: paw-arbeidssoekerregisteret-api-oppslag-unleash-api-token
  env:
    - name: OTEL_METRICS_EXPORTER
      value: "none"
    - name: OTEL_TRACES_EXPORTER
      value: "maskert_oltp"
    - name: OTEL_JAVAAGENT_DEBUG
      value: "false"
    - name: UNLEASH_SERVER_API_URL
      value: https://paw-unleash-api.nav.cloud.nais.io/api
  replicas:
    min: 1
    max: 1
  liveness:
    path: /internal/isAlive
    initialDelay: 10
  readiness:
    path: /internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    tracing:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: tokenx-token-generator
          namespace: aura
        - application: azure-token-generator
          namespace: aura
        - application: arena
          namespace: teamarenanais
          cluster: prod-fss
        - application: aia-backend
          namespace: paw
          cluster: prod-gcp
    outbound:
      rules:
        - application: poao-tilgang
          namespace: poao
      external:
        - host: paw-unleash-api.nav.cloud.nais.io
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: arbeidssoekerregisteretapioppslag